### ISSUE TITLE
`return energy/4.` or `return energy/2.` when calculating energy of Ising model?

### ISSUE THREAD

**Issue by WhymustIhaveaname** [rajeshrinet/compPhy#3]
I just found your [Ising model blog](https://rajeshrinet.github.io/blog/2014/ising-model/), which is very good and helped me a lot. However, I think the `return energy/4` in function `def calcEnergy(config)` should be divided by 2 because every link between sites is summed 2 times, not four.

**Comment by rajeshrinet** [comment]
@WhymustIhaveaname thanks very much interest and suggesting a fix. I agree with you that the factor should 2 instead of 2. I have now fixed the factor.

Best wishes,
Rajesh
